### ISSUE TITLE
File not completely opened when not UTF-8

### ISSUE THREAD

**Issue by pucicu** [unixwork/xnedit#16]
I face another problem: when I open a text file that is not UTF-8 (it is ISO8859-1) then I see a button which allows to reload with another encoding. However, the file is not completely opened. The last few lines are missing. I was not aware about this, simply changes the umlauts to have UTF-8 compatibility and saved the file, but then missing the last few lines.

**Comment by unixwork** [comment]
Thanks for the bug report. It should be fixed now.

I'm wondering why XNEdit wasn't detecting the file encoding, because normally ISO8859-1 encoded files should be opened without problems.

One problem is when a file is mixed with differend encodings. If half of the file is utf8 (with umlauts) and some ISO8859-1 umlauts are also in the file. Was this the case here?

**Comment by pucicu** [comment]
Now it works. Thanks! The files I have are actually not be mixed encoding.
