### ISSUE TITLE
some unicode characters not displayed in Titlebar

### ISSUE THREAD

**Issue by sebqas** [unixwork/xnedit#84]
When the character "ó" (#F3) is in the filename, the character itself and the
trailing  rest of the filename is not visible in the TitleBar. 
The same is for capital "Ó" (#D3) .
All other Polish characters are displayed properly.
Screen dumps:

!(https://github.com/sebqas/img/upload/wspólny.png) 
!(https://github.com/sebqas/img/upload/żółty.png) 

the property for TitleBar in nedit.rc is:
nedit.titleFormat: %d%f

xnedit v1.4

**Comment by unixwork** [comment]
Can you tell me which operating system and window manager you are using?

**Comment by sebqas** [comment]
Linux Mint, 19.1, WindowMaker 0.95.8

**Comment by unixwork** [comment]
I tried to reproduce this and fixed encoding problems in the titlebar, that were affecting some window managers, however on WindowMaker the problem still exists. Also, all applications that I tried have these problems on WindowMaker. What happens if you open the file in an application like Firefox, does the titlebar show all characters?
