### ISSUE TITLE
Unable to open non-UTF8 logs

### ISSUE THREAD

**Issue by andy9a9** [unixwork/xnedit#85]
I was trying to open the log file, but it wasn't possible.
![err_xnedit](https://user-images.githubusercontent.com/20794139/155976313-de982585-d92e-458d-bd9d-7a7b211ba1d7.png)

Input file [out.log](https://github.com/unixwork/xnedit/files/8152944/out.log)

**Comment by unixwork** [comment]
The file looks like normal ASCII or UTF-8 compatible. I think the problem is related to your environment, xnedit is reading some encoding information, which is "unset" in this case.

I could add a workaround for this, but I also would like to know how this happens. Which distribution are you using and what is the content of your LANG environment variable?

**Comment by andy9a9** [comment]
```
NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

LC_MONETARY=en_GB.UTF-8
LC_PAPER=en_GB.UTF-8
LANG=en_US.UTF-8
LC_TIME=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
```

**Comment by unixwork** [comment]
The environment looks normal, I think the "unset" encoding comes from editorconfig. I fixed a bug there, please test the newest version.

**Comment by andy9a9** [comment]
Even better, seems to be fixed ;)
Thanks!
