### ISSUE TITLE
contextual menu

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#94]
hi,
please add a contextual menu, right clicking on (selected) text, that show at least:
cut, copy, paste, ..., other

**Comment by unixwork** [comment]
Actually in the original nedit and in xnedit there is already a context menu, that contains all of that and is also customizable. The problem is, that it sometimes doesn't work. I believe it doesn't work if num-lock is active.

I don't know if this is an Xt, motif or xnedit bug. I also have no idea yet how to create a workaround for that.

**Comment by unixwork** [comment]
The newest commit should fix this issue.
